services:
#  banking-validation:
#    image: joao0212/banking-validation:v2
#    container_name: banking-validation-container
#    environment:
#      - QUARKUS_DATASOURCE_USERNAME=joao
#      - QUARKUS_DATASOURCE_PASSWORD=joao
#      - QUARKUS_DATASOURCE_HOST=postgres-db-alura
#      - QUARKUS_DATASOURCE_PORT=5432
#    ports:
#      - 8181:8181
#    depends_on:
#      - postgres-db-alura

  postgres-db-alura:
    image: postgres:14
    container_name: postgres-db-alura-container
    environment:
      - POSTGRES_USER=joao
      - POSTGRES_PASSWORD=joao
      - POSTGRES_DB=agencia
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin-db-alura:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-db-alura

  rabbit-mq:
    image: rabbitmq:3.10-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data:
    driver: local
